import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from 'next/head'
// import "./globals.css";
import Script from "next/script";
// import "/lib/animate/animate.min.css";
// import "/lib/owlcarousel/assets/owl.carousel.min.css";
// import "/lib/lightbox/css/lightbox.min.css";
// import "/css/bootstrap.min.css";
// import "/css/style.css";

// const inter = Inter({ subsets: ["latin"] });
import '../../public/css/bootstrap.min.css';
import '../../public/css/style.css';
import "../../public/scss/bootstrap.scss"

import { Suspense } from "react";
import Loading from "./loading";
import dynamic from "next/dynamic";
const Header = dynamic(() => import('@/components/core/Header'), {
  loading: () => <Loading/>,
})
const Footer = dynamic(() => import('@/components/core/Footer'), {
  loading: () => <Loading/>,
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <title>RayonWeb</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        {/* Favicon */}
        <link href="img/favicon.ico" rel="icon" />
        {/* Google Web Fonts */}
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" /> */}
        {/* <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500&family=Jost:wght@500;600;700&display=swap" rel="stylesheet" />  */}
        {/* Icon Font Stylesheet */}
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" integrity="sha512-dPXYcDub/aeb08c63jRq/k6GaKccl256JQy/AnOq7CAnEZ9FzSL9wSbcZkMp4R26vBsMLFYH4kQ67/bbV8XaCQ==" /> */}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/bootstrap-icons.svg" rel="stylesheet" />
        
        {/* Libraries Stylesheet */}
        <link href="/lib/animate/animate.min.css" rel="stylesheet" />
        <link href="/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
        <link href="/lib/lightbox/css/lightbox.min.css" rel="stylesheet" />
        {/* Customized Bootstrap Stylesheet */}
        {/* <link href="/css/bootstrap.min.css" rel="stylesheet" />
        {/* Template Stylesheet */}
        {/* <link href="/css/style.css" rel="stylesheet" /> */}
      </Head>
      <body >
        <Header />
        <Suspense fallback={<Loading/>}>
            {children}
        </Suspense>
        <Footer />
        <Script strategy="beforeInteractive" src="https://code.jquery.com/jquery-3.4.1.min.js"></Script>
        <Script strategy="afterInteractive" src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></Script>
        <Script strategy="beforeInteractive" src="lib/wow/wow.min.js"></Script>
        <Script strategy="beforeInteractive" src="lib/easing/easing.min.js"></Script>
        <Script strategy="beforeInteractive" src="lib/waypoints/waypoints.min.js"></Script>
        <Script strategy="afterInteractive" src="lib/counterup/counterup.min.js"></Script>
        <Script strategy="afterInteractive" src="lib/owlcarousel/owl.carousel.min.js"></Script>
        <Script strategy="afterInteractive" src="lib/isotope/isotope.pkgd.min.js"></Script>
        <Script strategy="afterInteractive" src="lib/lightbox/js/lightbox.min.js"></Script>

        {/* <!-- Template JavaScript --> */}
        <Script strategy="beforeInteractive" src="js/main.js"></Script>
      </body>
    </html>
  );
}
